# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Starship Docs - https://starship.rs/config/
#
# Current format
#
#â•­â”€jt@art ~/dev/dotfiles î‚  [x!?] +31 -1018                                      ó°½ 64% 18:33:38
#â•°â”€Î»                                                                                  took 3ms 

# Old theme. A modified Garuda Linux theme to occupy more vertical space.
#old_format = '''
#[â•­â”€](bold red)$username@$hostname at $time $battery
#[â”œ ](bold red)$directory
#[â”œ ](bold red)$git_branch$git_commit$git_state$git_status$git_metrics
#[â”œ ](bold red)($package )$c$golang$vlang$rust$zig$bun$nodejs$pulumi$terraform$gcloud
#[â”œ ]$cmd_duration $status
#[â•°â”€](bold red)$character
#'''

# Gohan theme
# purple = #7f3fbf
# blue = #279aff
# yellow = #fce983
# teal = #249470

format = '''
[â•­â”€](bold #7f3fbf)$username[@](bold )$hostname $directory $git_branch$git_commit$git_state$git_status$git_metrics$fill$battery $time
[â•°â”€](bold #7f3fbf)$character
'''

right_format = '''
$cmd_duration$status
'''

[fill]
symbol = ' '

### Line 1 - Username, Hostname, Directory, Time
[username]
format = "[$user]($style)"
show_always = true
style_root = "bold #7f3fbf"
style_user = "bold #7f3fbf"

[hostname]
disabled = false
format = "[$hostname]($style)"
ssh_only = false
style = "bold #7f3fbf"
trim_at = "-"

[sudo]
disabled = false

[time]
disabled = false
format = "$time($style)"
style = "bright-white"
time_format = "%T"

[battery]
disabled = false
format = "[$symbol$percentage]($style)"
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡ï¸"
discharging_symbol = "ğŸ’€"

[[battery.display]] # "bold red" style when capacity is between 0% and 15%
style = "bold red"
threshold = 15

[[battery.display]] # "bold yellow" style when capacity is between 15% and 50%
style = "bold #fce983"
threshold = 50

[[battery.display]] # "bold green" style when capacity is between 50% and 80%
style = "bold #249470"
threshold = 80

### Directory
[directory]
format = "[$path]($style)[$read_only]($read_only_style)"
style = "bold white"
truncate_to_repo = false
truncation_length = 5
truncation_symbol = "../"

### Git
[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style)"
style = "bold #7f3fbf"

[git_status]
ahead = "â‡¡${count}"
behind = "â‡£${count}"
deleted = "x"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
style = "#fce983"

[git_metrics]
disabled = false
added_style = "#279aff"
deleted_style = "#279aff"

### Packages, Languages/Runtimes
[package]
format = "[$symbol$version]($style)"


### Previous Command & Exit Status
[cmd_duration]
disabled = false
format = "[$duration]($style)"
min_time = 1
style = "#fce983"

[status]
disabled = false
format = ' [\[$status$status_common_meaning$status_signal_name$status_maybe_int\]]($style)'
map_symbol = true
pipestatus = true
symbol = "ğŸ”´"
style = "#fce983"

### Prompt
[character]
error_symbol = "[Ã—](bold red)"
success_symbol = "[Î»](bold #7f3fbf)"
