# art

## colours
#
# purple = #7f3fbf
# blue = #279aff
# yellow = #fce983
# teal = #249470

spacing = 2
padding = 0
hide_ascii = false
separator = "âœ"
key_color = "#7f3fbf"
separator_color = "#fce983"
prefer_small_ascii = true

[palette]
type = "Full"
glyph = "â–ˆâ–ˆâ–“"
visible = false

[bar]
glyph = "ß‹"
symbol_open = '['
symbol_close = ']'
hide_delimiters = true
visible = false

[box]
title = " macchina "
border = "plain"
visible = true

[box.inner_margin]
x = 2
y = 0

[randomize]
key_color = false
separator_color = false

[keys]
distro = "â‡  distro"
kernel = "âš™ï¸  kernel"
packages = "ğŸ“¦ packages"
terminal = "ğŸ—”  terminal"
shell = "ê©œ  shell"
machine = "ğŸ’» machine"
cpu = "âš”  cpu"
memory = "âš”  memory"
de = "ğŸ’» de"
wm = "ğŸ——  wm"
