# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Docs - https://starship.rs/config/
# Theme based off of Garuda Linux Starship theme.
# Modified to use more vertical space than horizontal.
#
# â•­â”€jthegedus@art in ~/dev/dotfiles at 16:18:34
# â”œ î‚  feat/garuda-starship-config [!?] +1 
# â”œ ğŸ“¦ v0.0.1 via V v0.3.2 
# â”œ Last command took 56ms 
# â•°â”€Î» 

format = """
[â•­â”€](bold red)$username@$hostname in $directory at $time$battery(\n[â”œ ](bold red)$git_branch$git_commit$git_state$git_status$git_metrics)(\n[â”œ ](bold red)($package )$c$golang$vlang$rust$zig$bun$nodejs$pulumi$terraform$gcloud)(\n$cmd_duration $status)
[â•°â”€](bold red)$character
"""

### Line 1 - Username, Hostname, Directory, Time
[username]
format = "[$user]($style)"
show_always = true
style_root = "bold red"
style_user = "bold red"

[hostname]
disabled = false
format = "[$hostname]($style)"
ssh_only = false
style = "bold dimmed red"
trim_at = "-"

[directory]
format = "[$path]($style)[$read_only]($read_only_style)"
style = "bold purple"
truncate_to_repo = false
truncation_length = 5
truncation_symbol = "../"

[sudo]
disabled = false

[time]
disabled = false
format = "$time($style)"
style = "bright-white"
time_format = "%T"

[battery]
disabled = false
format = "[$symbol$percentage]($style)"
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡ï¸"
discharging_symbol = "ğŸ’€"

[[battery.display]] # "bold red" style when capacity is between 0% and 15%
style = "bold red"
threshold = 15

[[battery.display]] # "bold yellow" style when capacity is between 15% and 50%
style = "bold yellow"
threshold = 50

[[battery.display]] # "bold green" style when capacity is between 50% and 80%
style = "bold green"
threshold = 80


### Line 2- Git
[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style)"
style = "bold purple"

[git_status]
ahead = "â‡¡${count}"
behind = "â‡£${count}"
deleted = "x"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
style = "white"

[git_metrics]
disabled = false


### Line 3 - Packages, Languages/Runtimes
[package]
format = "[$symbol$version]($style)"


### Line 4 - Previous Command & Exit Status
[cmd_duration]
disabled = false
format = "[â”œ ](bold red)Last command took [$duration]($style)"
min_time = 1

[status]
disabled = false
format = '& exited with [\[$status$status_common_meaning$status_signal_name$status_maybe_int\]]($style)'
map_symbol = true
pipestatus = true
symbol = "ğŸ”´"

### Line 5 - Prompt
[character]
error_symbol = "[Ã—](bold red)"
success_symbol = "[Î»](bold red)"
